site_name: WSDM Workshop on Benchmarking Causal Models (CausalBench'26)
nav:
  - Home: index.md
  - Visit CausalBench: "https://causalbench.org"

theme:
  name: mkdocs
  highlightjs: true
  color_mode: auto
  user_color_mode_toggle: true


